version: "3"

services:
  ortho-backend:
    image: "mongo:4.4.0"
    ports:
      - "27017:27017"
  ortho-service:
    ports:
      - "3000:3000"
    build:
      dockerfile: Dockerfile
      context: .
      args:
        PORT: ${PORT}
        SECRET: ${SECRET}
        NODE_ENV: ${NODE_ENV}
        DB_NAME: ${DB_NAME}
        MONGODB_URI: ${MONGODB_URI}
    depends_on:
      - ortho-backend
    links:
      - ortho-backend