version: '3'

services:
  ortho-backend:
    image: "mongo:4.4.0"
    ports:
      - "27017:27017"
  ortho-service:
    ports:
      - "3000:3000"
    build:
      dockerfile: Dockerfile
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
        DB_NAME: ${DB_NAME}
        MONGODB_URI: ${MONGODB_URI}
        SERVICE_PORT: ${SERVICE_PORT}
        SERVICE_SECRET: ${SERVICE_SECRET}
    depends_on:
      - ortho-backend
    links:
      - ortho-backend